---
title: "Book 2 - A Clash of Kings"
---

```{r}
library(dplyr)
library(readr)
library(tidytext)
library(ggplot2)
library(tidyr)
library(wordcloud)
```


```{r}
book_2 <- read_file("~/Downloads/book 2.txt")
book_2_df <- tibble(text=book_2)
```


```{r}
lines_book2<-
  book_2_df%>%
  unnest_tokens(sentence, text, token="sentences")%>%
  mutate(linenumber = row_number()) %>%
  unnest_tokens(word, sentence)%>%
  slice(308:n())%>%
  slice(1:319968)
```

```{r}
plotsentiment_bing <- lines_book2 %>%
  inner_join(get_sentiments("bing")) %>%
  count(index = linenumber %/% 80, sentiment) %>%
  spread(sentiment, n, fill = 0) %>%
  mutate(sentiment = positive - negative)

plotsentiment_nrc<-
  lines_book2 %>%
  inner_join(get_sentiments("nrc")) %>%
  count(index = linenumber %/% 80, sentiment) %>%
  spread(sentiment, n, fill = 0) %>%
  mutate(sentiment = positive - negative)

plotsentiment_afinn <- lines_book2 %>% 
  inner_join(get_sentiments("afinn")) %>% 
  group_by(index = linenumber %/% 80) %>% 
  summarise(sentiment = sum(score)) 



ggplot(plotsentiment_bing, aes(index, sentiment)) +
  geom_col(show.legend = FALSE) 

ggplot(plotsentiment_nrc, aes(index, sentiment)) +
  geom_col(show.legend = FALSE) 

ggplot(plotsentiment_afinn, aes(index, sentiment)) +
  geom_col(show.legend = FALSE) 
```


```{r}
tidy_book2<-
  book_2_df%>%
  unnest_tokens(word, text)%>%
  slice(308:n())%>%
  slice(1:319968)
```

```{r}

```




```{r}
#Freqency
data(stop_words)

custom_stop_words <- bind_rows(data_frame(word = c("stark", "lord", "ser", "king"), 
                                          lexicon = c("custom")), 
                               stop_words)

freq_book2<-
  tidy_book2%>%
  anti_join(custom_stop_words)%>%
  count(word, sort = TRUE)
```

```{r}
filter_book2<-
  freq_book2%>%
  filter(n > 350) %>%
  mutate(word = reorder(word, n))
ggplot(data=filter_book2, aes(word, n)) + geom_col() + xlab(NULL) + coord_flip()
```

```{r}
#Sentiment analysis

characters<-read_csv("~/Downloads/A Song of Ice and Fire Character Spreadsheet - Characters.csv")

bing_and_nrc <- bind_rows(tidy_book2 %>% 
                            inner_join(get_sentiments("bing")) %>%
                            anti_join(custom_stop_words)%>%
                            mutate(method = "Bing et al."),
                          tidy_book2 %>% 
                            inner_join(get_sentiments("nrc") %>% 
                            anti_join(custom_stop_words)%>%
                            filter(sentiment %in% c("positive","negative"))) %>%
                            mutate(method = "NRC")) %>%
  count(method, sentiment) %>%
  spread(sentiment, n, fill = 0) %>%
  mutate(sentiment = positive - negative)%>%
  mutate(positive=NA, negative=NA)

afinn <- tidy_book2 %>%
  inner_join(get_sentiments("afinn")) %>% 
  mutate(method = "AFINN")%>%
  anti_join(custom_stop_words)%>%
  group_by(method)%>%
  summarise(sentiment=sum(score))

sentiment_join<-
    bind_rows(afinn, bing_and_nrc)

allsentiment<-
  bind_rows(tidy_book2 %>% 
                            inner_join(get_sentiments("bing")) %>%
                            mutate(method = "Bing et al."),
                          tidy_book2 %>% 
                            inner_join(get_sentiments("nrc") %>% 
                            filter(sentiment %in% c("positive","negative"))) %>%
                            mutate(method = "NRC"))%>%
  count(word, sentiment, sort = TRUE) %>%
  ungroup()%>%
  anti_join(custom_stop_words)
  
top_sentiment<-
  allsentiment%>%
  group_by(sentiment) %>%
  top_n(10) %>%
  ungroup() %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(word, n, fill = sentiment)) +
  geom_col(show.legend = FALSE) +
  facet_wrap(~sentiment, scales = "free_y") +
  labs(y = "Contribution to sentiment",
       x = NULL) +
  coord_flip()

allsentiment
  



got_sentiment<-read_tsv("~/Downloads/subreddits/asoiaf.tsv", col_names = c("word", "mean", "std"))

reddit <- tidy_book2 %>%
  inner_join(got_sentiment) %>% 
  mutate(method = "reddit")%>%
  group_by(method)%>%
  summarise(sentiment=sum(mean))


nrc <- sentiments %>% filter(lexicon == "nrc")
tidy_book2 %>% 
  inner_join(nrc) %>% 
  count(sentiment)%>%
  arrange(desc(n))

#need to have each word associated with line number in order to look at sentiment analysis over course of book
```
```{r}
wordcloud<-
  wordcloud(freq_book2$word,             
          freq_book2$n,                
          scale=c(3,0.2),
          min.freq = 2,
          max.words=200,                  
          random.order=FALSE,             
          colors=brewer.pal(8, "Set1"))



library(reshape2)

sentiment_cloud<-
  allsentiment%>%
  acast(word ~ sentiment, value.var = "n", fill = 0) %>%
  comparison.cloud(colors = c("#F8766D", "#00BFC4"),scale=c(3,0.2), max.words=200, random.order=FALSE)
```

